### ISSUE TITLE
[Question] Plugins

### ISSUE THREAD

**Issue by MTRNord** [Spferical/matrix-chatbot#2]
Are plugins supported or is this project WIP?

**Comment by Spferical** [comment]
I would say they're out of scope. My intention with this project was just to make a chatterbot that listens in channels and occasionally responds. The only commands it understands right now are ones that relate to this behavior, and nothing else is planned.

If you're interested in an extensible bot with commands and services, https://github.com/matrix-org/go-neb is a good place to look.

**Comment by MTRNord** [comment]
Ok thanks for info :)
