### ISSUE TITLE
How to train the bot?

### ISSUE THREAD

**Issue by k-sathireddy** [Spferical/matrix-chatbot#3]
Can anyone specify how to train the bot with sample example? I couldn't get the bot.

**Comment by Spferical** [comment]
Right now, to train the bot, you provide a text file. The bot assumes that you have one message per line in the file, and nothing else. (Also no extra stuff, like usernames or dates or things that might be in IRC logs or similar).

Simple example:
```
$ echo "This is a line of training text.\nThis is another line." > training.txt
$ python2 main.py --train training.txt
2017-04-21 23:08:55,824 root INFO loading brain
Training...
Training complete!
$
```

Sadly, I don't have any sample texts you can use. When training my instance of the bot I used some conversation logs stretching back a few years. You can use anything that comes in a text file.

Also note that training is not completely necessary. The bot also learns by passively listening in chatrooms, even if it starts out not knowing anything.

Hope that helps!
